config/routes.rb
Rails.application.routes.draw do
  # Root route
  root 'pages#index'

  # Sessions routes
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  # Pages routes
  get 'pages/index'

  # Collection points routes
  get 'collection_points/search', to: 'collection_points#search'
  get 'collection_points/nearby', to: 'collection_points#nearby'
  resources :collection_points

  # Other resources
  resources :users
  resources :recyclable_materials
end

app/models/collection_point.rb
class CollectionPoint < ApplicationRecord
  has_and_belongs_to_many :recyclable_materials

  scope :search, lambda { |query|
    if query.present?
      where('name ILIKE ?', "%#{query}%")
    else
      all
    end
  }
end

app/controllers/collection_points_controller.rb
class CollectionPointsController < ApplicationController
  before_action :set_collection_point, only: %i[show edit update destroy]

  def index
    @collection_points = CollectionPoint.all
  end

  def show; end

  def new
    @collection_point = CollectionPoint.new
    @recyclable_materials = RecyclableMaterial.all
  end

  def edit
    @recyclable_materials = RecyclableMaterial.all
  end

  def create
    @collection_point = CollectionPoint.new(collection_point_params)

    respond_to do |format|
      if @collection_point.save
        format.html { redirect_to collection_points_url, notice: 'Collection point was successfully created.' }
        format.json { render :show, status: :created, location: @collection_point }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @collection_point.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @collection_point.update(collection_point_params)
        format.html { redirect_to collection_points_url, notice: 'Collection point was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection_point }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @collection_point.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @collection_point.destroy

    respond_to do |format|
      format.html { redirect_to collection_points_url, notice: 'Collection point was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Método para pesquisar pontos de coleta com base em uma consulta de nome ou material reciclável
  def search
    query = params[:query].strip.downcase
    @collection_points = CollectionPoint.joins(:recyclable_materials)
                                        .where('lower(collection_points.name) LIKE :query OR lower(recyclable_materials.name) LIKE :query', query: "%#{query}%")
                                        .distinct
    render json: @collection_points.as_json(include: :recyclable_materials)
  end

  # Método responsável por buscar os pontos de coleta próximos à localização informada pelo usuário
  def nearby
    lat = params[:latitude].to_f
    lng = params[:longitude].to_f
    radius = 10 * 1000 # 10 km de raio

    @collection_points = CollectionPoint.select('*')
                                        .from("collection_points, (SELECT '#{lat}'::float AS lat, '#{lng}'::float AS lng) AS user_location")
                                        .where("earth_distance(ll_to_earth(collection_points.latitude, collection_points.longitude), ll_to_earth(user_location.lat, user_location.lng)) <= #{radius}")
                                        .includes(:recyclable_materials)

    render json: @collection_points.as_json(include: :recyclable_materials)
  end

  private

  def set_collection_point
    @collection_point = CollectionPoint.find(params[:id])
  end

  def collection_point_params
    params.require(:collection_point).permit(:name, :address, :latitude, :longitude, :contact, :website,
                                             recyclable_material_ids: [])
  end
end

app/helpers/collection_points_helper.rb
module CollectionPointsHelper
end

app/views/collection_points/_collection_point.html.erb
<div id="<%= dom_id collection_point %>" class="card">
  <div class="card-content">
    <span class="card-title"><strong>Name:</strong></span>
    <p><%= collection_point.name %></p>
    <span class="card-title"><strong>Address:</strong></span>
    <p><%= collection_point.address %></p>
    <span class="card-title"><strong>Latitude:</strong></span>
    <p><%= collection_point.latitude %></p>
    <span class="card-title"><strong>Longitude:</strong></span>
    <p><%= collection_point.longitude %></p>
    <span class="card-title"><strong>Contact:</strong></span>
    <p><%= collection_point.contact %></p>
    <span class="card-title"><strong>Website:</strong></span>
    <p><%= collection_point.website %></p>
  </div>
</div>

app/views/collection_points/_form.html.erb
  <%= form_with(model: collection_point) do |form| %>
  <% if collection_point.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(collection_point.errors.count, "error") %> prohibited this collection_point from being saved:</h2>
      <ul>
        <% collection_point.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col s12 m8 offset-m2">
      <div class="input-field">
        <%= form.label :name, class: ('active' if collection_point.name.present?) %>
        <%= form.text_field :name, class: "validate" %>
      </div>
      <div class="input-field">
        <%= form.label :address, class: ('active' if collection_point.address.present?) %>
        <%= form.text_field :address %>
      </div>
      <div class="input-field">
        <%= form.label :latitude, class: ('active' if collection_point.latitude.present?) %>
        <%= form.text_field :latitude %>
      </div>
      <div class="input-field">
        <%= form.label :longitude, class: ('active' if collection_point.longitude.present?) %>
        <%= form.text_field :longitude %>
      </div>
      <div class="input-field">
        <%= form.label :contact, class: ('active' if collection_point.contact.present?) %>
        <%= form.text_field :contact %>
      </div>
      <div class="input-field">
        <%= form.label :website, class: ('active' if collection_point.website.present?) %>
        <%= form.text_field :website %>
      </div>
      <div>
        <%= form.label "Materials", style: "display: block" %>
        <% @recyclable_materials.each do |material| %>
          <p>
            <label>
              <%= check_box_tag "collection_point[recyclable_material_ids][]", material.id, collection_point.recyclable_material_ids.include?(material.id), class: "filled-in", id: "collection_point_recyclable_material_ids_#{material.id}" %>
              <span><%= material.name %></span>
            </label>
          </p>
        <% end %>
      </div>
      <div>
        <%= form.submit class: "btn waves-effect waves-light" %> <%= link_to "Back to Collection Points", collection_points_path, class: "btn" %>
      </div>
    </div>
  </div>
<% end %>

app/views/collection_points/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col s12">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Editing Collection Points</span>
        </div>
      </div>
      <br/>
      <div class="row">
        <div class="col s12 m8 offset-m2">
          <%= render "form", collection_point: @collection_point %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/collection_points/index.html.erb
<div class="container-fluid">
  <% if notice.present? %>
    <div class="row">
      <div class="col s12">
        <div class="card-panel green lighten-2">
          <span class="white-text"><%= notice %></span>
        </div>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="col s12">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Collection Points<%= link_to "New", new_collection_point_path, class: "btn right" %></span>
        </div>
      </div>
      <div class="table-responsive bordered">
        <table class="striped">
          <thead>
            <tr>
              <th>Name</th>
              <th>Address</th>
              <th>Contact</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @collection_points.each do |collection_point| %>
              <tr id="<%= dom_id collection_point %>">
                <td><%= collection_point.name %></td>
                <td><%= truncate(collection_point.address, length: 50) %></td>
                <td><%= collection_point.contact %></td>
                <td class="right-align">
                  <%= link_to 'Show', collection_point, class: "btn" %>
                  <%= link_to 'Edit', edit_collection_point_path(collection_point), class: "btn" %>
                  <%= link_to 'Destroy', collection_point, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn red darken-1" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/collection_points/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col s12">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">New Collection Points</span>
        </div>
      </div>
      <br/>
      <div class="row">
        <div class="col s12 m8 offset-m2">
          <%= render "form", collection_point: @collection_point %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/collection_points/show.html.erb
<div class="container-fluid">
  <% if notice.present? %>
    <div class="row">
      <div class="col s12">
        <div class="card-panel green lighten-2">
          <span class="white-text"><%= notice %></span>
        </div>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="col s12">
      <%= render @collection_point %>
      <div>
        <%= link_to "Edit", edit_collection_point_path(@collection_point), class: "btn" %> <%= link_to "Back to Collection Points", collection_points_path, class: "btn" %>
      </div>
    </div>
  </div>
</div>