config/routes.rb
Rails.application.routes.draw do
  # Root route
  root 'pages#index'

  # Sessions routes
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  # Pages routes
  get 'pages/index'

  # Collection points routes
  get 'collection_points/search', to: 'collection_points#search'
  get 'collection_points/nearby', to: 'collection_points#nearby'
  resources :collection_points

  # Other resources
  resources :users
  resources :recyclable_materials
end

app/models/recyclable_material.rb
class RecyclableMaterial < ApplicationRecord
  has_and_belongs_to_many :collection_points
end

app/controllers/recyclable_materials_controller.rb
class RecyclableMaterialsController < ApplicationController
  before_action :set_recyclable_material, only: %i[show edit update destroy]

  def index
    @recyclable_materials = RecyclableMaterial.all
  end

  def show; end

  def new
    @recyclable_material = RecyclableMaterial.new
  end

  def edit; end

  def create
    @recyclable_material = RecyclableMaterial.new(recyclable_material_params)

    respond_to do |format|
      if @recyclable_material.save
        format.html do
          redirect_to recyclable_materials_url,
                      notice: 'Recyclable material was successfully created.'
        end
        format.json { render :show, status: :created, location: @recyclable_material }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recyclable_material.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @recyclable_material.update(recyclable_material_params)
        format.html do
          redirect_to recyclable_materials_url,
                      notice: 'Recyclable material was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @recyclable_material }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recyclable_material.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recyclable_material.destroy

    respond_to do |format|
      format.html { redirect_to recyclable_materials_url, notice: 'Recyclable material was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_recyclable_material
    @recyclable_material = RecyclableMaterial.find(params[:id])
  end

  def recyclable_material_params
    params.require(:recyclable_material).permit(:name, :description, :category)
  end
end

app/helpers/recyclable_materials_helper.rb
module RecyclableMaterialsHelper
end

app/views/recyclable_materials/_form.html.erb
  <%= form_with(model: recyclable_material) do |form| %>
  <% if recyclable_material.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recyclable_material.errors.count, "error") %> prohibited this recyclable_material from being saved:</h2>
      <ul>
        <% recyclable_material.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col s12 m8 offset-m2">
      <div class="input-field">
        <%= form.label :name, class: ('active' if recyclable_material.name.present?), style: "display: block" %>
        <%= form.text_field :name, class: "validate" %>
      </div>
      <div class="input-field">
        <%= form.label :description, class: ('active' if recyclable_material.description.present?), style: "display: block" %>
        <%= form.text_area :description, class: "materialize-textarea validate" %>
      </div>
      <div class="input-field">
        <%= form.label :category, class: ('active' if recyclable_material.category.present?), style: "display: block" %>
        <%= form.text_field :category, class: "validate" %>
      </div>
      <div>
        <%= form.submit class: "btn waves-effect waves-light" %> <%= link_to "Back to Recyclable Materials", recyclable_materials_path, class: "btn" %>
      </div>
    </div>
  </div>
<% end %>

app/views/recyclable_materials/_recyclable_material.html.erb
<div id="<%= dom_id recyclable_material %>" class="card">
  <div class="card-content">
    <span class="card-title"><strong>Name:</strong></span>
    <p><%= recyclable_material.name %></p>
    <span class="card-title"><strong>Description:</strong></span>
    <p><%= recyclable_material.description %></p>
    <span class="card-title"><strong>Category:</strong></span>
    <p><%= recyclable_material.category %></p>
  </div>
</div>

app/views/recyclable_materials/edit.html.erb
<h1>Editing recyclable material</h1>

<%= render "form", recyclable_material: @recyclable_material %>

<br>

<div>
  <%= link_to "Show this recyclable material", @recyclable_material %> |
  <%= link_to "Back to recyclable materials", recyclable_materials_path %>
</div>

app/views/recyclable_materials/index.html.erb
<div class="container-fluid">
  <% if notice.present? %>
    <div class="row">
      <div class="col s12">
        <div class="card green lighten-2">
          <div class="card-content white-text">
            <%= notice %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="col s12">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Recyclable Materials<%= link_to "New", new_recyclable_material_path, class: "btn right" %></span>
        </div>
      </div>
      <div class="table-responsive bordered">
        <table class="striped">
          <thead>
            <tr>
              <th>Name</th>
              <th>Category</th>
              <th>Description</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @recyclable_materials.each do |recyclable_material| %>
              <tr id="<%= dom_id recyclable_material %>">
                <td><%= recyclable_material.name %></td>
                <td><%= recyclable_material.category %></td>
                <td><%= recyclable_material.description %></td>
                <td class="right-align">
                  <%= link_to 'Show', recyclable_material, class: "btn" %>
                  <%= link_to 'Edit', edit_recyclable_material_path(recyclable_material), class: "btn" %>
                  <%= link_to 'Destroy', recyclable_material, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn red darken-1" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/recyclable_materials/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col s12">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">New Recyclable Material</span>
        </div>
      </div>
      <br/>
      <div class="row">
        <div class="col s12 m8 offset-m2">
          <%= render "form", recyclable_material: @recyclable_material %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/recyclable_materials/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recyclable_material %>

<div>
  <%= link_to "Edit this recyclable material", edit_recyclable_material_path(@recyclable_material) %> |
  <%= link_to "Back to recyclable materials", recyclable_materials_path %>

  <%= button_to "Destroy this recyclable material", @recyclable_material, method: :delete %>
</div>