config/routes.rb
Rails.application.routes.draw do
  # Root route
  root 'pages#index'

  # Sessions routes
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  # Pages routes
  get 'pages/index'

  # Collection points routes
  get 'collection_points/search', to: 'collection_points#search'
  get 'collection_points/nearby', to: 'collection_points#nearby'
  resources :collection_points

  # Other resources
  resources :users
  resources :recyclable_materials
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecyclingMap</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'https://unpkg.com/leaflet@1.9.3/dist/leaflet.css', media: "all", "data-turbolinks-track": "reload" %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/icon?family=Material+Icons', media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'https://unpkg.com/leaflet@1.9.3/dist/leaflet.js' %>
  </head>
  <body>
    <% unless hide_menu? %>
      <nav>
        <div class="nav-wrapper">
          <a href="#" class="brand-logo">Recycling Map</a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><%= link_to "Collection Points", collection_points_path %></li>
            <li><%= link_to "Recyclable Materials", recyclable_materials_path %></li>
            <li><%= link_to "Users", users_path %></li>
            <% if current_user %>
              <li><%= link_to "Logout", logout_path, method: :delete %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    <% end %>
    <%= yield %>
  </body>
</html>